FROM nginx:alpine

# REMOVE COMPLETAMENTE a página padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia nossa página personalizada
COPY build/index.html /usr/share/nginx/html/index.html

# Copia configuração do nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Expõe porta 8080
EXPOSE 8080

# Inicia nginx
CMD ["nginx", "-g", "daemon off;"]
