FROM nginx:alpine

# Remover COMPLETAMENTE o conteúdo padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiar TODO o build do React AgroSync
COPY build/ /usr/share/nginx/html/

# Copiar configuração customizada do nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Expor porta 80
EXPOSE 80

# Comando para iniciar nginx
CMD ["nginx", "-g", "daemon off;"]
