/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'display': ['Orbitron', 'Space Grotesk', 'Inter', 'sans-serif'],
        'heading': ['Orbitron', 'Space Grotesk', 'Inter', 'sans-serif'],
        'body': ['Inter', 'Poppins', 'sans-serif'],
        'ui': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
        'outfit': ['Outfit', 'sans-serif'],
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'orbitron': ['Orbitron', 'Space Grotesk', 'Outfit', 'sans-serif'],
      },
      colors: {
        // Cores premium para o site mais bonito da internet
        'premium': {
          'black': '#000000', // Preto fosco (fundo)
          'dark': '#0a0a0a',
          'darker': '#050505',
          'light': '#ffffff',
          'neon-blue': '#00F0FF', // Azul metálico ou neon (títulos, animações, detalhes vivos)
          'neon-cyan': '#00FFFF',
          'neon-green': '#00FF7F', // Verde neon (destaques, animações suaves, microinterações)
          'neon-purple': '#8A2BE2', // Roxo ou dourado suave
          'neon-gold': '#FFD700',
          'neon-pink': '#FF1493',
          'neon-orange': '#FF6B35',
          'neon-yellow': '#FFFF00',
          'neon-red': '#FF0000',
          'neon-white': '#FFFFFF',
          'neon-gray': '#808080',
          'neon-dark': '#1a1a1a',
          'neon-darker': '#0d0d0d',
          'neon-light': '#f0f0f0',
          'neon-lighter': '#ffffff',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // AGROTM Fixed Colors - Atualizadas para premium
        'agro-dark': '#000000',
        'agro-darker': '#000000',
        'agro-light': '#ffffff',
        'agro-primary': '#00F0FF',
        'agro-secondary': '#00FF7F',
        'agro-accent': '#8A2BE2',
        'agro-green': '#00FF7F',
        'agro-blue': '#00F0FF',
        'agro-purple': '#8A2BE2',
        'agro-yellow': '#FFD700',
        'agro-red': '#FF6B35',
        'agro-gray': '#cccccc',
        'agro-gray-light': '#cccccc',
        'agro-gray-dark': '#cccccc',
        'agro-neon': '#00F0FF',
        'neonBlue': '#00F0FF',
        'neon-blue': '#00F0FF',
        'neon-cyan': '#00FFFF',
        'neon-azul': '#00F0FF',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'bounce-in': 'bounceIn 0.6s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'pulse-neon': 'pulseNeon 2s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'gradient': 'gradient 8s linear infinite',
        'cyber-grid': 'cyberGrid 20s linear infinite',
        'neon-flicker': 'neonFlicker 3s ease-in-out infinite',
        'hologram': 'hologram 4s ease-in-out infinite',
        'matrix': 'matrix 10s linear infinite',
        'spin-slow': 'spin 3s linear infinite',
        'spin-reverse': 'spin 1s linear infinite reverse',
        'bounce-slow': 'bounce 2s infinite',
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'tilt': 'tilt 10s infinite linear',
        'orbit': 'orbit 20s linear infinite',
        'ripple': 'ripple 1s linear infinite',
        'wave': 'wave 2s ease-in-out infinite',
        'morph': 'morph 8s ease-in-out infinite',
        'blob': 'blob 7s infinite',
        'float-1': 'float 6s ease-in-out infinite',
        'float-2': 'float 6s ease-in-out infinite 1s',
        'float-3': 'float 6s ease-in-out infinite 2s',
        'glow-1': 'glow 2s ease-in-out infinite alternate',
        'glow-2': 'glow 2s ease-in-out infinite alternate 0.5s',
        'glow-3': 'glow 2s ease-in-out infinite alternate 1s',
        'shimmer-1': 'shimmer 2.5s linear infinite',
        'shimmer-2': 'shimmer 2.5s linear infinite 0.5s',
        'shimmer-3': 'shimmer 2.5s linear infinite 1s',
        'gradient-1': 'gradient 8s linear infinite',
        'gradient-2': 'gradient 8s linear infinite 2s',
        'gradient-3': 'gradient 8s linear infinite 4s',
        'cyber-grid-1': 'cyberGrid 20s linear infinite',
        'cyber-grid-2': 'cyberGrid 20s linear infinite 5s',
        'cyber-grid-3': 'cyberGrid 20s linear infinite 10s',
        'neon-flicker-1': 'neonFlicker 3s ease-in-out infinite',
        'neon-flicker-2': 'neonFlicker 3s ease-in-out infinite 1s',
        'neon-flicker-3': 'neonFlicker 3s ease-in-out infinite 2s',
        'hologram-1': 'hologram 4s ease-in-out infinite',
        'hologram-2': 'hologram 4s ease-in-out infinite 1s',
        'hologram-3': 'hologram 4s ease-in-out infinite 2s',
        'matrix-1': 'matrix 10s linear infinite',
        'matrix-2': 'matrix 10s linear infinite 2s',
        'matrix-3': 'matrix 10s linear infinite 4s',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceIn: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 20px rgba(0, 240, 255, 0.5)' },
          '100%': { boxShadow: '0 0 40px rgba(0, 240, 255, 0.8), 0 0 60px rgba(0, 240, 255, 0.3)' },
        },
        pulseNeon: {
          '0%, 100%': { 
            textShadow: '0 0 10px rgba(0, 240, 255, 0.5), 0 0 20px rgba(0, 240, 255, 0.3)' 
          },
          '50%': { 
            textShadow: '0 0 20px rgba(0, 240, 255, 0.8), 0 0 30px rgba(0, 240, 255, 0.5), 0 0 40px rgba(0, 240, 255, 0.3)' 
          },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        cyberGrid: {
          '0%': { transform: 'translate(0, 0)' },
          '100%': { transform: 'translate(50px, 50px)' },
        },
        neonFlicker: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        hologram: {
          '0%, 100%': { 
            opacity: '0.8',
            transform: 'translateY(0px) scale(1)',
            filter: 'hue-rotate(0deg)'
          },
          '50%': { 
            opacity: '1',
            transform: 'translateY(-10px) scale(1.02)',
            filter: 'hue-rotate(180deg)'
          },
        },
        matrix: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        tilt: {
          '0%, 50%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(0.5deg)' },
          '75%': { transform: 'rotate(-0.5deg)' },
        },
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(20px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(20px) rotate(-360deg)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        wave: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(20deg)' },
          '75%': { transform: 'rotate(-20deg)' },
        },
        morph: {
          '0%, 100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'cyber-grid': 'linear-gradient(rgba(0, 240, 255, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(0, 240, 255, 0.1) 1px, transparent 1px)',
        'neon-gradient': 'linear-gradient(135deg, #00F0FF 0%, #00FF7F 50%, #8A2BE2 100%)',
        'premium-gradient': 'linear-gradient(135deg, #000000 0%, #0a0a0a 50%, #1a1a1a 100%)',
        'hologram-gradient': 'linear-gradient(45deg, #00F0FF, #00FFFF, #00FF7F, #8A2BE2, #00F0FF)',
        'cyber-gradient': 'linear-gradient(45deg, #00F0FF 0%, #00FFFF 25%, #00FF7F 50%, #8A2BE2 75%, #00F0FF 100%)',
        'neon-blue-gradient': 'linear-gradient(135deg, #00F0FF 0%, #00FFFF 100%)',
        'neon-green-gradient': 'linear-gradient(135deg, #00FF7F 0%, #00FFFF 100%)',
        'neon-purple-gradient': 'linear-gradient(135deg, #8A2BE2 0%, #00F0FF 100%)',
        'neon-gold-gradient': 'linear-gradient(135deg, #FFD700 0%, #FFA500 100%)',
        'neon-pink-gradient': 'linear-gradient(135deg, #FF1493 0%, #FF69B4 100%)',
        'neon-orange-gradient': 'linear-gradient(135deg, #FF6B35 0%, #FF8C00 100%)',
        'neon-yellow-gradient': 'linear-gradient(135deg, #FFFF00 0%, #FFD700 100%)',
        'neon-red-gradient': 'linear-gradient(135deg, #FF0000 0%, #FF4500 100%)',
        'neon-white-gradient': 'linear-gradient(135deg, #FFFFFF 0%, #F0F0F0 100%)',
        'neon-gray-gradient': 'linear-gradient(135deg, #808080 0%, #A0A0A0 100%)',
        'neon-dark-gradient': 'linear-gradient(135deg, #1a1a1a 0%, #0d0d0d 100%)',
        'neon-darker-gradient': 'linear-gradient(135deg, #0d0d0d 0%, #000000 100%)',
        'neon-light-gradient': 'linear-gradient(135deg, #f0f0f0 0%, #ffffff 100%)',
        'neon-lighter-gradient': 'linear-gradient(135deg, #ffffff 0%, #f8f8f8 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'neon-blue': '0 0 20px rgba(0, 240, 255, 0.5)',
        'neon-green': '0 0 20px rgba(0, 255, 127, 0.5)',
        'neon-purple': '0 0 20px rgba(138, 43, 226, 0.5)',
        'premium': '0 0 40px rgba(0, 240, 255, 0.3)',
        'cyber': '0 0 30px rgba(0, 240, 255, 0.2), inset 0 0 30px rgba(0, 240, 255, 0.1)',
        'neon-gold': '0 0 20px rgba(255, 215, 0, 0.5)',
        'neon-pink': '0 0 20px rgba(255, 20, 147, 0.5)',
        'neon-orange': '0 0 20px rgba(255, 107, 53, 0.5)',
        'neon-yellow': '0 0 20px rgba(255, 255, 0, 0.5)',
        'neon-red': '0 0 20px rgba(255, 0, 0, 0.5)',
        'neon-white': '0 0 20px rgba(255, 255, 255, 0.5)',
        'neon-gray': '0 0 20px rgba(128, 128, 128, 0.5)',
        'neon-dark': '0 0 20px rgba(26, 26, 26, 0.5)',
        'neon-darker': '0 0 20px rgba(13, 13, 13, 0.5)',
        'neon-light': '0 0 20px rgba(240, 240, 240, 0.5)',
        'neon-lighter': '0 0 20px rgba(255, 255, 255, 0.5)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [],
};
