# AGROISYNC Yarn Configuration
nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: mixed
enableScripts: true
enableStrictSsl: true
enableTelemetry: false
enableImmutableInstalls: true
enableInlineBuilds: true
enableInlineScripts: true
enableNetwork: true
enablePreferInteractive: false
enablePreferOffline: true
enableProgressBars: false
enableRc: true
