packages:
  - 'frontend'
  - 'backend'
  - 'contracts'
  - 'api'
  - 'staking'
  - 'defi-dashboard'
  - 'agro-intel'
  - 'ai'
  - 'analytics'
  - 'enterprise'
  - 'microservices/*'
  - 'go/microservices/*'
  - 'python/scripts/*'
  - 'security'
