AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AGROISYNC Backend (Lambda + HTTP API) - Production Ready

Parameters:
  StripeSecretKey:
    Type: String
    Description: Stripe Secret Key for payments
    NoEcho: true
  MetamaskAddress:
    Type: String
    Description: Metamask wallet address for admin operations
    Default: "0x5Ea5C5970e8AE23A5336d631707CF31C5916E8b1"
  Environment:
    Type: String
    Description: Environment (dev/staging/prod)
    Default: "production"
    AllowedValues: ["dev", "staging", "production"]
  DatabasePassword:
    Type: String
    Description: Database password
    NoEcho: true
  JWTSecret:
    Type: String
    Description: JWT secret key
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        UPLOAD_BUCKET: !Ref UploadBucket
        DYNAMODB_TABLE_PREFIX: "agroisync"
        LOG_LEVEL: "info"
        CORS_ORIGIN: "*"
        RATE_LIMIT_WINDOW_MS: "900000"
        RATE_LIMIT_MAX_REQUESTS: "100"

Resources:
  # Main API Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "agroisync-api-${Environment}"
      CodeUri: .
      Handler: dist/handler.js
      MemorySize: 2048
      Timeout: 60
      ReservedConcurrencyLimit: 100
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Alarms:
          - !Ref ApiFunctionErrorAlarm
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:PutObjectAcl
              Resource: !Sub "arn:aws:s3:::${UploadBucket}/*"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/agroisync-*"
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerSecret
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"
      Environment:
        Variables:
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          METAMASK_ADMIN_ADDRESS: !Ref MetamaskAddress
          JWT_SECRET: !Ref JWTSecret
          DB_PASSWORD: !Ref DatabasePassword
          UPLOAD_BUCKET: !Ref UploadBucket
          DYNAMODB_TABLE_PREFIX: "agroisync"
          LOG_LEVEL: "info"
          CORS_ORIGIN: "*"
          RATE_LIMIT_WINDOW_MS: "900000"
          RATE_LIMIT_MAX_REQUESTS: "100"
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE

  # Health Check Function
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "agroisync-health-${Environment}"
      CodeUri: .
      Handler: dist/health-handler.js
      MemorySize: 512
      Timeout: 10
      ReservedConcurrencyLimit: 50
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/agroisync-*"
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          AWS_REGION: !Ref AWS::Region
          DYNAMODB_TABLE_PREFIX: "agroisync"
      Events:
        HealthCheck:
          Type: HttpApi
          Properties:
            Path: /health
            Method: GET

  # Secrets Manager for sensitive data
  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "agroisync-secrets-${Environment}"
      Description: "AGROISYNC application secrets"
      SecretString: !Sub |
        {
          "stripe_secret_key": "${StripeSecretKey}",
          "jwt_secret": "${JWTSecret}",
          "database_password": "${DatabasePassword}",
          "metamask_admin_address": "${MetamaskAddress}"
        }

  # S3 Bucket for file uploads
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "agroisync-uploads-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, POST, PUT, DELETE, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3000
            ExposedHeaders: ["ETag", "x-amz-meta-custom-header"]
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: DeleteOldObjects
            Status: Enabled
            ExpirationInDays: 365
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: "agroisync"

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "agroisync-users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: wallet_address
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: WalletIndex
          KeySchema:
            - AttributeName: wallet_address
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: "agroisync"

  StakingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "agroisync-staking-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: pool_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: PoolIndex
          KeySchema:
            - AttributeName: pool_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: "agroisync"

  # CloudWatch Alarms
  ApiFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "agroisync-api-errors-${Environment}"
      AlarmDescription: "Alarm when API function has errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiFunction
      AlarmActions:
        - !Ref SNSTopic

  # SNS Topic for notifications
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "agroisync-alerts-${Environment}"
      DisplayName: !Sub "AGROISYNC Alerts - ${Environment}"

  # CloudWatch Dashboard
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "agroisync-dashboard-${Environment}"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${ApiFunction}"],
                  [".", "Errors", ".", "."],
                  [".", "Throttles", ".", "."]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Function Metrics"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${UsersTable}"],
                  [".", "ConsumedWriteCapacityUnits", ".", "."]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Metrics"
              }
            }
          ]
        }

Outputs:
  ApiUrl:
    Description: HTTP API URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "agroisync-api-url-${Environment}"
  
  UploadBucketName:
    Description: S3 Bucket for file uploads
    Value: !Ref UploadBucket
    Export:
      Name: !Sub "agroisync-upload-bucket-${Environment}"
  
  UsersTableName:
    Description: DynamoDB table for users
    Value: !Ref UsersTable
    Export:
      Name: !Sub "agroisync-users-table-${Environment}"
  
  StakingTableName:
    Description: DynamoDB table for staking
    Value: !Ref StakingTable
    Export:
      Name: !Sub "agroisync-staking-table-${Environment}"
  
  SecretsManagerArn:
    Description: Secrets Manager ARN
    Value: !Ref SecretsManagerSecret
    Export:
      Name: !Sub "agroisync-secrets-arn-${Environment}"
  
  SNSTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref SNSTopic
    Export:
      Name: !Sub "agroisync-sns-topic-${Environment}"
