AWSTemplateFormatVersion: '2010-09-09'
Description: AGROISYNC Backend - Working Lambda + API Gateway

Parameters:
  Environment:
    Type: String
    Default: "production"
    AllowedValues: ["dev", "staging", "production"]

Resources:
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "agroisync-lambda-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda Function - WORKING CODE
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "agroisync-api-${Environment}"
      Runtime: nodejs20.x
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log('Event:', JSON.stringify(event, null, 2));
            
            try {
              const path = event.path || event.rawPath || '/';
              const method = event.httpMethod || event.requestContext?.http?.method || 'GET';
              
              console.log(`Path: ${path}, Method: ${method}`);
              
              // Health check
              if (path === '/health' || path === '/') {
                return {
                  statusCode: 200,
                  headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
                    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS'
                  },
                  body: JSON.stringify({
                    message: 'AGROISYNC API funcionando perfeitamente! 🚀',
                    environment: process.env.ENVIRONMENT || 'production',
                    timestamp: new Date().toISOString(),
                    path: path,
                    method: method,
                    status: 'healthy'
                  })
                };
              }
              
              // API routes
              if (path.startsWith('/api')) {
                return {
                  statusCode: 200,
                  headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
                    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS'
                  },
                  body: JSON.stringify({
                    message: 'AGROISYNC API Route funcionando! 🎯',
                    path: path,
                    method: method,
                    timestamp: new Date().toISOString(),
                    data: {
                      service: 'agroisync',
                      version: '2.3.1',
                      features: ['crypto', 'grains', 'marketplace', 'freight']
                    }
                  })
                };
              }
              
              // Default response
              return {
                statusCode: 200,
                headers: {
                  'Content-Type': 'application/json',
                  'Access-Control-Allow-Origin': '*',
                  'Access-Control-Allow-Headers': 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',
                  'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS'
                },
                body: JSON.stringify({
                  message: 'AGROISYNC API - Rota não encontrada, mas funcionando! 🔍',
                  path: path,
                  method: method,
                  timestamp: new Date().toISOString(),
                  availableRoutes: ['/health', '/api/*', '/']
                })
              };
              
            } catch (error) {
              console.error('Error:', error);
              return {
                statusCode: 500,
                headers: {
                  'Content-Type': 'application/json',
                  'Access-Control-Allow-Origin': '*'
                },
                body: JSON.stringify({
                  message: 'Erro interno do servidor',
                  error: error.message,
                  timestamp: new Date().toISOString()
                })
              };
            }
          };
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "agroisync-api-${Environment}"
      Description: AGROISYNC Backend API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource for proxy
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method for proxy
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations"

  # API Gateway Method for root
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations"

  # Lambda Permission for API Gateway
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*"

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - ApiMethod
      - RootMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

Outputs:
  ApiUrl:
    Description: "URL da API"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
  LambdaFunctionArn:
    Description: "ARN da função Lambda"
    Value: !GetAtt ApiFunction.Arn
  HealthCheckUrl:
    Description: "URL do Health Check"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/health"
