name: production
on:
  workflow_run:
    workflows: ["AGROTM CI/CD Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: echo "Production deployment completed" 