name: Staging Environment
description: Staging deployment environment for AGROISYNC
workflows: ["AGROISYNC CI/CD Pipeline"]
on:
  workflow_run:
    workflows: ["AGROISYNC CI/CD Pipeline"]
    types:
      - completed
    branches: [develop]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Deploy to staging
      run: echo "Staging deployment completed" 