// Auto-generated by scripts/csp-hashes.js
export default [
  "sha256-Srpsq4/mM3KOTP/su5/kjhG/GWbcE1yGL46weGv/AxU=",
  "sha256-Dn3TLb0tNNUHyBkY81F0/l+gGWx68I+v7+ZCdmKIBLU=",
  "sha256-KSlKHojEaJnx+WaLI7nC/4EqxQZjjl6EkQ7cgyXAZ+A=",
  "sha256-hgPIIH/YqZcnZfKnLNnuInjwbWbMYjee20NRnQtHtMA=",
  "sha256-kbEWGz5jgZQBcRSYWjwozj8kwktaKdtG7GrXBjh0nF0=",
  "sha256-HKAaz86BQ7s+1hD/eCyaE+K3rAp4OXtk4SzF8Ke1AWU=",
  "sha256-Yn0/1kgjZNQu5qgigcNWbJ4P4zPfjLG+A9VtpOeqUT0=",
  "sha256-bpmpSMKHTO4+QFFeljhItMDwsH4rMZiuPX6/UjuYHAo="
];
