const { createHash } = require('crypto');

function sha256Base64(s) {
  return 'sha256-' + createHash('sha256').update(s, 'utf8').digest('base64');
}

// These payloads mirror the exact JSON.stringify outputs in the pages
const payloads = [
  // Organization (used in multiple pages)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Agroisync",
    url: "https://agroisync.com",
    logo: "https://agroisync.com/agroisync-logo.svg",
  }),
  // WebSite (home)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Agroisync",
    url: "https://agroisync.com/",
    publisher: {
      "@type": "Organization",
      name: "Agroisync",
      logo: { "@type": "ImageObject", url: "https://agroisync.com/agroisync-logo.svg" },
    },
  }),
  // WebSite (contato)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Agroisync",
    url: "https://agroisync.com",
  }),
  // Breadcrumbs: home only (index)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
    ],
  }),
  // Breadcrumbs: sobre
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Sobre", item: "https://agroisync.com/sobre" },
    ],
  }),
  // Breadcrumbs: marketplace
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Marketplace", item: "https://agroisync.com/marketplace" },
    ],
  }),
  // Breadcrumbs: fretes
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Fretes", item: "https://agroisync.com/fretes" },
    ],
  }),
  // Breadcrumbs: contato
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Contato", item: "https://agroisync.com/contato" },
    ],
  }),
];

const hashes = payloads.map(sha256Base64);
const fs = require('fs');
const path = require('path');
const outPath = path.join(__dirname, '..', 'csp-hashes.js');
const content = `// Auto-generated by scripts/csp-hashes.js\nmodule.exports = ${JSON.stringify(hashes, null, 2)};\n`;
fs.writeFileSync(outPath, content);
console.log('Wrote', outPath, 'with', hashes.length, 'hashes');
