const { createHash } = require('crypto');

function sha256Base64(s) {
  return 'sha256-' + createHash('sha256').update(s, 'utf8').digest('base64');
}

// These payloads mirror the exact JSON.stringify outputs in the pages
const payloads = [
  // Organization (used in multiple pages)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Agroisync",
    url: "https://agroisync.com",
    logo: "https://agroisync.com/agroisync-logo.svg",
  }),
  // WebSite (home)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Agroisync",
    url: "https://agroisync.com/",
    publisher: {
      "@type": "Organization",
      name: "Agroisync",
      logo: { "@type": "ImageObject", url: "https://agroisync.com/agroisync-logo.svg" },
    },
  }),
  // WebSite (contato)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Agroisync",
    url: "https://agroisync.com",
  }),
  // Breadcrumbs: home only (index)
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
    ],
  }),
  // Breadcrumbs: sobre
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Sobre", item: "https://agroisync.com/sobre" },
    ],
  }),
  // Breadcrumbs: produtos
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Produtos", item: "https://agroisync.com/produtos" },
    ],
  }),
  // Breadcrumbs: fretes
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Fretes", item: "https://agroisync.com/frete" },
    ],
  }),
  // Breadcrumbs: contato
  JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://agroisync.com/" },
      { "@type": "ListItem", position: 2, name: "Contato", item: "https://agroisync.com/contato" },
    ],
  }),
];

const hashes = payloads.map(sha256Base64);
const fs = require('fs');
const path = require('path');
const outPath = path.join(__dirname, '..', 'src', 'utils', 'csp-hashes.js');
const content = `// Auto-generated by scripts/csp-hashes.js
export default ${JSON.stringify(hashes, null, 2)};
`;

// Criar diretório se não existir
const dir = path.dirname(outPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(outPath, content);
console.log('Wrote', outPath, 'with', hashes.length, 'hashes');
